"""empty message

Revision ID: 6423e47fe354
Revises: 0763d677d453
Create Date: 2025-06-11 07:31:28.524300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6423e47fe354'
down_revision = '0763d677d453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fullname', sa.String(), nullable=False))
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.drop_column('fullname')

    # ### end Alembic commands ###
